### ISSUE TITLE
i can not running the script

### ISSUE THREAD

**Issue by KKopf** [fusonic/opengraph#26]
i have create a composer.json and i have installed (cmd console) the scripts with "php composer.phar install"

![1](https://user-images.githubusercontent.com/8206765/82153171-31559580-9866-11ea-9cfd-ee054135fdf1.jpg)

then i running the script with an error:

Fatal error: Uncaught Error: Class 'Fusonic\OpenGraph\Consumer' not found in C:\xampp\htdocs\meta\website.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\meta\website.php on line 5

here the complete code from my php file:

```
<?php

use Fusonic\OpenGraph\Consumer;

$consumer = new Consumer($httpClient, $httpRequestFactory);
$object = $consumer->loadUrl("http://www.computerbase.de");

// Basic information of the object
echo "Title: " . $object->title;                // Getting started with Facebook Open Graph
echo "Site name: " . $object->siteName;         // YouTube
echo "Description: " . $object->description;    // Originally recorded at the Facebook World ...
echo "Canonical URL: " . $object->url;          // http://www.youtube.com/watch?v=P422jZg50X4

// Images
$image = $object->images[0];
echo "Image[0] URL: " . $image->url;             // https://i1.ytimg.com/vi/P422jZg50X4/maxresdefault.jpg
echo "Image[0] height: " . $image->height;       // null (May return height in pixels on other pages)
echo "Image[0] width: " . $image->width;         // null (May return width in pixels on other pages)

// Videos
$video = $object->videos[0];
echo "Video URL: " . $video->url;               // http://www.youtube.com/v/P422jZg50X4?version=3&autohide=1
echo "Video height: " . $video->height;          // 1080
echo "Video width: " . $video->width;            // 1920
echo "Video type: " . $video->type;            // application/x-shockwave-flash
?>
```

line 5:

`$consumer = new Consumer($httpClient, $httpRequestFactory);`

here my folder content:

![2](https://user-images.githubusercontent.com/8206765/82153341-20f1ea80-9867-11ea-9d36-b89d6276da56.jpg)

[edit]

i have now modification the first lines in my script with:

```
<?php
require('vendor/autoload.php');
use Fusonic\OpenGraph\Consumer;
```
now comes an other error message:

Notice: Undefined variable: httpClient in C:\xampp\htdocs\meta\website.php on line 8

Notice: Undefined variable: httpRequestFactory in C:\xampp\htdocs\meta\website.php on line 8

`Fatal error: Uncaught LogicException: To use loadUrl() you must provide $client and $requestFactory when instantiating the consumer. in C:\xampp\htdocs\meta\vendor\fusonic\opengraph\src\Consumer.php:57 Stack trace: #0 C:\xampp\htdocs\meta\website.php(9): Fusonic\OpenGraph\Consumer->loadUrl('http://www.comp...') #1 {main} thrown in C:\xampp\htdocs\meta\vendor\fusonic\opengraph\src\Consumer.php on line 57`

and how can i solve that problem?

**Comment by mburtscher** [comment]
@KKopf You have to first initialize both a HTTP client and a HTTP request factory. You can use the code from [here](https://github.com/fusonic/opengraph/blob/master/examples/consume_website.php).

But for that to work you have to run `php composer.phar require symfony/http-client nyholm/psr7`.
