### ISSUE TITLE
Release v1 to have stable dependencies

### ISSUE THREAD

**Issue by ecorica** [fusonic/opengraph#27]
Hello, can you tag your v1 with stable dependencies?
I work in php 7.2 and I would like to use your library :)

**Comment by mburtscher** [comment]
I had to have a look at the composer documentation to figure out what you mean. Is my assumption right, that the used `~X.X` and `^X.X` version constraint notation is problematic, since it allows dev releases?

https://getcomposer.org/doc/articles/versions.md#stability-constraints
