### ISSUE TITLE
Certain Sites Only Work When facebookexternalhit/1.1 User-Agent Is Specified

### ISSUE THREAD

**Issue by kachi1227** [fusonic/opengraph#28]
First of all, great library! Thanks for putting it together.

So earlier this year, Twitter stopped sending down open graph data unless specific user-agents were specified. The only one that I've gotten to work is the 'facebookexternalhit/1.1' user-agent and it should, in theory, work forever since it's the user-agent that the Facebook crawler uses. Unfortunately for me, I figured this out after a considerable amount of debugging on my end. In order to save users time, it might be helpful to update the code in the examples folder to the following:
`$client = new Psr18Client(new NativeHttpClient(['headers'=>['User-Agent'=>'facebookexternalhit/1.1']]));`

In case you're wondering, I've tested the code above with all major websites (Google, Facebook, CNN, Twitter, Youtube, Instagram, Amazon, etc) and they all return valid open graph data.

Attached are screenshots of the open graph data that gets returned when the following url is passed: https://twitter.com/CNN/status/1308170698175774720. The first screenshot is the result without a user-agent and the second screenshot is the result with the user-agent mentioned above.

**No User-Agent:**
<img width="238" alt="Screen Shot 2020-09-21 at 6 50 03 PM" src="https://user-images.githubusercontent.com/5930412/93829753-5440ed80-fc3c-11ea-904d-5b46036c0170.png">

**facebookexternalhit/1.1 User-Agent:**
<img width="857" alt="Screen Shot 2020-09-21 at 6 50 45 PM" src="https://user-images.githubusercontent.com/5930412/93829779-6a4eae00-fc3c-11ea-8dfc-6511b9ac4178.png">

**Comment by mburtscher** [comment]
Well, this is interesting. I think I'll add a user-agent option which defaults to `facebookexternalhit/1.1`.

**Comment by mburtscher** [comment]
Since client configuration is outside the library I think it wouldn't be a good idea to modify the client after it is passed to the `Consumer`. So I've added a note in the README and updated the example code.

Thank you for analyzing the issue and explaining so well!

**Comment by johnchristopher** [comment]
> `$client = new Psr18Client(new NativeHttpClient(['headers'=>['User-Agent'=>'facebookexternalhit/1.1']]));`
> 
> In case you're wondering, I've tested the code above with all major websites (Google, Facebook, CNN, Twitter, Youtube, Instagram, Amazon, etc) and they all return valid open graph data.

This user-agent is banned/403ed on some European newspaper websites. Eg.: https://lesoir.be/. Symfony or Guzzle default client is not and then meta and og can be read. I ended up adding a switch depending on the host.
