### ISSUE TITLE
Not compatiable with Laravel 8

### ISSUE THREAD

**Issue by Seriyyy95** [fusonic/opengraph#32]
Maybe you should allow use version symfony/css-selector to 6.0.

Problem 1
    - Root composer.json requires fusonic/opengraph dev-master -> satisfiable by fusonic/opengraph[dev-master].
    - fusonic/opengraph dev-master requires symfony/css-selector ^3.0|^4.0|^5.0 -> found symfony/css-selector[v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by mburtscher** [comment]
Thanks for pointing it out, fixed in 2.2.0.
