### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by whitsey** [fusonic/opengraph#33]
Installed `fusonic/opengraph` package and used the example (https://github.com/fusonic/opengraph) to Retrieve Open Graph data from a URL successfully.

I have since found that one of the 15 sites I am checking returns a 403 Forbidden error so I decided to try and set the User Agent to overcome this issue.

I referenced the example: `examples/consume_website.php` BUT, when I use the example and add:

```
use Symfony\Component\HttpClient\NativeHttpClient;
use Symfony\Component\HttpClient\Psr18Client;

// Initialize new Psr\HttpClient implementation. This example uses Symfony's implementation from the symfony/http-client
// package but you can use any implementation provided by your framework of choice.
$client = new Psr18Client(new NativeHttpClient([ "headers" => [ "User-Agent" => "facebookexternalhit/1.1" ] ]));
```

I get the following error:

`PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\HttpClient\Psr18Client' not found in /api/get-media.php`

Symfony was installed with Opengraph ... Is there a separate package not referenced in the example I need to install?

**Comment by whitsey** [comment]
<html>
<body>
<h1 class="brand-font font-size-xtra no-margin" style="margin: 0px 0px 30px; padding: 0px; box-sizing: inherit; font-size: 36px; line-height: 1; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Access Denied - Sucuri Website Firewall</h1><p class="medium-text code-snippet" style="margin: 30px 0px 45px; padding: 18px; box-sizing: inherit; border: 1px solid grey; background-color: rgb(247, 247, 247); box-shadow: rgba(0, 0, 0, 0.2) 0px 1px 4px 0px; border-radius: 8px; font-size: 16px; clear: both; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">If you are the site owner (or you manage this site), please whitelist your IP or if you think this block is an error please<span> </span><a href="https://support.sucuri.net/?utm_source=firewall_block" class="color-green underline" style="margin: 0px; padding: 0px; box-sizing: inherit; color: rgb(96, 159, 67); text-decoration: none;">open a support ticket</a><span> </span>and make sure to include the block details (displayed in the box below), so we can assist you in troubleshooting the issue.</p><h2 style="margin: 0px 0px 10px; padding: 0px; box-sizing: inherit; font-size: 25px; color: rgb(34, 34, 34); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Block details:</h2>

Your IP: | xx.xx.xx.xxx
-- | --
Your Browser: | GuzzleHttp/6.5.5 curl/7.83.1 PHP/7.3.33
Block ID: | BNP005
Block reason: | Bad bot access attempt.
Time: | 2022-06-28 01:15:37
Server ID: | 601


</body>
</html>Access Denied - Sucuri Website Firewall
If you are the site owner (or you manage this site), please whitelist your IP or if you think this block is an error please [open a support ticket](https://support.sucuri.net/?utm_source=firewall_block) and make sure to include the block details (displayed in the box below), so we can assist you in troubleshooting the issue.

Block details:
Your IP:	xx.xx.xx.xxx
Your Browser:	GuzzleHttp/6.5.5 curl/7.83.1 PHP/7.3.33
Block ID:	BNP005
Block reason:	Bad bot access attempt.
Time:	2022-06-28 01:15:37
Server ID:	601

**Comment by mburtscher** [comment]
Hello @whitsey, if you check out this repository and run a `composer install` everything should work fine in the examples. But the `symfony/http-client` package is only a suggested package since you might want to use a different PSR18 implementation. Maybe you have tried to run the example in the context of your personal project and there is no `symfony/http-client` package installed?

The second issue seems to be related to the browser string which can be changed just as you have mentioned in your initial issue description.

**Comment by mburtscher** [comment]
You can use `symfony/http-client` in version 5.x which only requires PHP >= 7.2.5. [This post on StackOverflow](https://stackoverflow.com/questions/40914114/how-to-install-a-specific-version-of-package-using-composer) contains information on how to require a specific version.
