### ISSUE TITLE
Encoding issue with Google Drive links

### ISSUE THREAD

**Issue by Rudloff** [fusonic/opengraph#9]
Hello,
I get encoding issues with Google Drive links.
Here is a test case: https://docs.google.com/document/d/1tQmgMwLmr4418beGOAH3fEH5a5vBj-6PI_SB0Uh9Vd0/edit?usp=sharing

`loadHtml` extracts this description:

> Ceci est un test : Ã©Ã Ã©

**Comment by mburtscher** [comment]
Test file is not available anymore.
